# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pivotTableTemplate.ui'
#
# Created: Mon Jan 14 20:27:50 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1050, 684)
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(380, 630, 341, 31))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.splitter = QtGui.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(9, 9, 361, 521))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.listFields = QtGui.QListWidget(self.verticalLayoutWidget_2)
        self.listFields.setTabKeyNavigation(True)
        self.listFields.setDragEnabled(True)
        self.listFields.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listFields.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listFields.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.listFields.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listFields.setObjectName(_fromUtf8("listFields"))
        self.verticalLayout_2.addWidget(self.listFields)
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ColLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.ColLabel.setObjectName(_fromUtf8("ColLabel"))
        self.verticalLayout.addWidget(self.ColLabel)
        self.listCols = QtGui.QListWidget(self.verticalLayoutWidget)
        self.listCols.setTabKeyNavigation(True)
        self.listCols.setDragEnabled(True)
        self.listCols.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listCols.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listCols.setObjectName(_fromUtf8("listCols"))
        self.verticalLayout.addWidget(self.listCols)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.listRows = QtGui.QListWidget(self.verticalLayoutWidget)
        self.listRows.setTabKeyNavigation(True)
        self.listRows.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listRows.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listRows.setObjectName(_fromUtf8("listRows"))
        self.verticalLayout.addWidget(self.listRows)
        self.RowLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.RowLabel.setObjectName(_fromUtf8("RowLabel"))
        self.verticalLayout.addWidget(self.RowLabel)
        self.listValues = QtGui.QListWidget(self.verticalLayoutWidget)
        self.listValues.setTabKeyNavigation(True)
        self.listValues.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listValues.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listValues.setObjectName(_fromUtf8("listValues"))
        self.verticalLayout.addWidget(self.listValues)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 539, 351, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.update = QtGui.QPushButton(self.layoutWidget)
        self.update.setObjectName(_fromUtf8("update"))
        self.horizontalLayout.addWidget(self.update)
        self.MakePT = QtGui.QPushButton(self.layoutWidget)
        self.MakePT.setObjectName(_fromUtf8("MakePT"))
        self.horizontalLayout.addWidget(self.MakePT)
        self.displayTable = QtGui.QTableWidget(Dialog)
        self.displayTable.setGeometry(QtCore.QRect(570, 20, 451, 501))
        self.displayTable.setObjectName(_fromUtf8("displayTable"))
        self.displayTable.setColumnCount(0)
        self.displayTable.setRowCount(0)
        self.listFilters = QtGui.QListWidget(Dialog)
        self.listFilters.setGeometry(QtCore.QRect(390, 10, 161, 511))
        self.listFilters.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.listFilters.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listFilters.setObjectName(_fromUtf8("listFilters"))
        self.MakeFilter = QtGui.QPushButton(Dialog)
        self.MakeFilter.setGeometry(QtCore.QRect(390, 540, 98, 27))
        self.MakeFilter.setObjectName(_fromUtf8("MakeFilter"))
        self.FilterName = QtGui.QTextEdit(Dialog)
        self.FilterName.setGeometry(QtCore.QRect(380, 580, 341, 31))
        self.FilterName.setObjectName(_fromUtf8("FilterName"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.update, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.updateState)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.initialise)
        QtCore.QObject.connect(self.listCols, QtCore.SIGNAL(_fromUtf8("itemActivated(QListWidgetItem*)")), Dialog.updateFilters)
        QtCore.QObject.connect(self.listFields, QtCore.SIGNAL(_fromUtf8("itemActivated(QListWidgetItem*)")), Dialog.updateFilters)
        QtCore.QObject.connect(self.listRows, QtCore.SIGNAL(_fromUtf8("itemActivated(QListWidgetItem*)")), Dialog.updateFilters)
        QtCore.QObject.connect(self.listValues, QtCore.SIGNAL(_fromUtf8("itemActivated(QListWidgetItem*)")), Dialog.updateFilters)
        QtCore.QObject.connect(self.MakeFilter, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.createFilter)
        QtCore.QObject.connect(self.MakePT, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.makePT)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "PandasPTGui", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.ColLabel.setText(QtGui.QApplication.translate("Dialog", "Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Rows", None, QtGui.QApplication.UnicodeUTF8))
        self.RowLabel.setText(QtGui.QApplication.translate("Dialog", "Values", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "setState", None, QtGui.QApplication.UnicodeUTF8))
        self.update.setText(QtGui.QApplication.translate("Dialog", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.MakePT.setText(QtGui.QApplication.translate("Dialog", "MakePT", None, QtGui.QApplication.UnicodeUTF8))
        self.MakeFilter.setText(QtGui.QApplication.translate("Dialog", "MakeFilter", None, QtGui.QApplication.UnicodeUTF8))

